<<<<<<< HEAD
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
=======
theme: jekyll-theme-tactile
>>>>>>> 2ccaa67 (Create _config.yml)
title: EHR Phenotyping workshop
description: SSC workshop
